ci/projects/urls.py
from django.conf.urls.defaults import patterns, url

from . import views


urlpatterns = patterns('',
    url(r'^$', views.projects, name='projects'),

    url(r'^add/$', views.add_project, name='add_project'),

    url(r'^project/(?P<slug>[\w_-]+)/admin/$',
        views.project_admin, name='project_admin'),

    url(r'^project/(?P<slug>[\w_-]+)/axis/$',
        views.project_axis, name='project_axis'),

    url(r'^project/(?P<slug>[\w_-]+)/build/$',
        views.project_trigger_build, name='project_trigger_build'),

    url(r'^project/(?P<slug>[\w_-]+)/builds/(?P<pk>\d+)/delete/$',
        views.delete_build, name='delete_build'),

    url(r'^project/(?P<slug>[\w_-]+)/builds/(?P<pk>\d+)/jobs/(?P<job_id>\d+)/$',
        views.job, name='project_job'),

    url(r'^project/(?P<slug>[\w_-]+)/builds/(?P<pk>\d+)/$',
        views.project_build, name='project_build'),

    url(r'^project/(?P<slug>[\w_-]+)/builds/$',
        views.project_builds, name='project_builds'),

    url(r'^project/(?P<slug>[\w_-]+)/$', views.project, name='project'),
)

ci/projects/models.py
import anyjson as json
import datetime
import itertools
import logging
import os
import shutil

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _

from .. import vcs
from ..exceptions import CommandError
from ..shell import Command
from ..parsers import XunitParser

logger = logging.getLogger('ci')


class Project(models.Model):
    GIT = 'git'
    HG = 'hg'

    REPO_TYPES = (
        (GIT, _('Git')),
        (HG, _('Mercurial')),
    )

    ALL_BRANCHES = 'all'
    DEFAULT_BRANCH = 'default'

    BRANCHES = (
        (DEFAULT_BRANCH, _('Default branch')),
        (ALL_BRANCHES, _('All')),
    )

    name = models.CharField(_('Name'), max_length=255)
    slug = models.SlugField(_('Slug'), max_length=255, unique=True)

    repo = models.CharField(
        _('Repository'), max_length=1024,
        help_text=_('The clone or checkout URL of your repository'),
    )
    repo_type = models.CharField(_('Repository type'), max_length=10,
                                 choices=REPO_TYPES, default=GIT)
    build_instructions = models.TextField(
        _('Build instructions'),
        help_text=_('The commands that need to be run in order to build the '
                    'project. The instructions are run from the root of your '
                    'repository. If you have mutliple configurations to run, '
                    'you can configure build axis separately.'),
    )
    sequential = models.BooleanField(
        _('Sequential build?'), default=True,
        help_text=_('Check this box to disallow parallel builds.'),
    )
    keep_build_data = models.BooleanField(
        _('Keep build data'), default=False,
        help_text=_('Check this box to keep build data on disk. Useful for '
                    'debugging builds but potentially eats a lot of disk '
                    'space.'),
    )
    xunit_xml_report = models.CharField(_('XML test report'), blank=True,
                                        max_length=1023)
    build_branches = models.CharField(_('Branches to build'), max_length=50,
                                      choices=BRANCHES, default=DEFAULT_BRANCH)

    class Meta:
        ordering = ('name',)

    def __unicode__(self):
        return u'%s' % self.name

    def save(self, *args, **kwargs):
        clone = self.pk is None
        super(Project, self).save(*args, **kwargs)
        if clone:
            from .tasks import clone_on_creation
            clone_on_creation.delay(self.pk)

    def get_absolute_url(self):
        return reverse('project', args=[self.slug])

    def vcs(self):
        return {
            self.GIT: vcs.Git,
            self.HG: vcs.Hg,
        }[self.repo_type](self.repo, self.cache_dir)

    @property
    def cache_dir(self):
        """
        Directory where to put the local clone.
        """
        prefix = os.path.join(settings.WORKSPACE, 'repos')
        if not os.path.exists(prefix):
            os.makedirs(prefix)
        return os.path.join(prefix, self.slug)

    def build(self):
        """
        Triggers a build!

        Returns True if the build is triggered, False if not
        (revisions are not built twice).
        """
        self.update_source()
        vcs = self.vcs()
        branches = ([vcs.default_branch]  # TODO detect repo's default branch
                    if self.build_branches == self.DEFAULT_BRANCH
                    else vcs.branches())

        jobs = []
        for branch in branches:
            branch_jobs = self.build_branch(branch)
            if branch_jobs is not None:
                jobs = list(itertools.chain(jobs, branch_jobs))

        if jobs and self.sequential:
            from .tasks import execute_jobs
            execute_jobs.delay([j.pk for j in jobs])
        else:
            for job in jobs:
                job.queue()
        return bool(jobs)

    def build_branch(self, branch):
        rev = self.vcs().latest_branch_revision(branch)
        if self.builds.filter(branch=branch, revision=rev).exists():
            # Latest rev already build -- don't bother
            return
        configs = self.configurations.all()
        if configs:
            products = []
            matrix = {}
            for config in configs:
                matrix[config.key] = []
                values = config.values.all()
                products.append(values)
                for val in values:
                    matrix[config.key].append(val.value)
            items = itertools.product(*products)
        else:
            matrix = {}

        # Attach some history info. If the branch hasn't been built yet,
        # forget about history -- we don't want to walk through the
        # entire repo.
        same_branch = self.builds.filter(branch=branch)
        if same_branch:
            history = self.vcs().changelog(branch, same_branch[0].revision)
        else:
            history = []

        build = Build.objects.create(
            project=self,
            revision=rev,
            branch=branch,
            matrix=json.dumps(matrix),
            history=json.dumps([c.serializable for c in history]),
            build_instructions=self.build_instructions,
            xunit_xml_report=self.xunit_xml_report,
        )
        jobs = []

        if configs:
            for values in items:
                job = Job.objects.create(
                    build=build,
                    values=json.dumps({v.key.key: v.value for v in values}),
                )
                jobs.append(job)
        else:
            job = Job.objects.create(
                build=build,
            )
            jobs.append(job)
        return jobs

    def update_source(self):
        """
        Projects keep a full clone / checkout of the upstream repo for
        polling changes.
        """
        self.vcs().update_source()

    @property
    def latest_revision(self):
        """
        Fetch the latest revision from SCM
        """
        vcs = self.vcs()
        vcs.update_source()
        return vcs.latest_revision()

    @property
    def build_status(self):
        """
        Success or failure? Or maybe still running...
        """
        if not self.builds.exists():
            return _('no build yet')
        return self.builds.all()[0].build_status

    def build_progress(self):
        builds = self.builds.all()[0].jobs.all()
        total = len(builds)
        done = len([b for b in builds if b.status in (b.SUCCESS, b.FAILURE)])
        return '%s/%s' % (done, total)

    def axis_initial(self):
        """
        Returns the initial data for axis forms.
        """
        initial = []
        for axis in self.configurations.all():
            initial.append({
                'name': axis.key,
                'values': ', '.join(map(unicode, axis.values.all())),
            })
        return initial


class Configuration(models.Model):
    """
    Multi-configurations ala jenkins: a key, several values, a build per value.
    """
    project = models.ForeignKey(Project, verbose_name=_('Project'),
                                related_name='configurations')
    key = models.CharField(_('Key'), max_length=255)

    def __unicode__(self):
        return u'%s' % self.key

    class Meta:
        unique_together = ('project', 'key')


class Value(models.Model):
    key = models.ForeignKey(Configuration, verbose_name=_('Key'),
                            related_name='values')
    value = models.CharField(_('Value'), max_length=255)

    def __unicode__(self):
        return u'%s' % self.value

    class Meta:
        unique_together = ('key', 'value')


class Build(models.Model):
    """
    Stores the metadata for a build axis / matrix
    """
    project = models.ForeignKey(Project, verbose_name=_('Project'),
                                related_name='builds')
    revision = models.CharField(_('Revision built'), max_length=1023)
    branch = models.CharField(_('Branch'), max_length=1023)
    creation_date = models.DateTimeField(_('Date created'),
                                         default=datetime.datetime.now)
    history = models.TextField(_('Changelog'), blank=True)

    # These fields are serialized from the project. Lets users safely alter
    # config values when a build has already been trigerred: the build
    # has everything it needs.
    matrix = models.TextField(_('Build matrix'), blank=True)
    build_instructions = models.TextField(_('Build instructions'))
    xunit_xml_report = models.CharField(_('XML test report'), blank=True,
                                        max_length=1023)

    def __unicode__(self):
        return u'Build #%s of %s' % (self.pk, self.project.name)

    class Meta:
        ordering = ('-creation_date',)

    def queue(self):
        """
        Trigger a sequential build.
        """
        from .tasks import execute_jobs
        job_ids = list(self.jobs.values_list('pk', flat=True))
        execute_jobs.delay(job_ids)

    @property
    def matrix_data(self):
        """
        Returns the build matrix, json-loaded.
        """
        return json.loads(self.matrix)

    @property
    def history_data(self):
        return json.loads(self.history)

    @property
    def build_status(self):
        builds = self.jobs.all()
        running = [build for build in builds if build.status == build.RUNNING]
        if running:
            return 'running'
        failed = [build for build in builds if build.status == build.FAILURE]
        if failed:
            return 'failed'
        success = [build for build in builds if build.status == build.SUCCESS]
        if success:
            return 'success'
        pending = [build for build in builds if build.status == build.PENDING]
        if pending:
            return 'pending'
        return 'not running. not failed. not success. not pending. what is it?'

    @property

ci/projects/templates/projects/build_confirm_delete.html
{% extends "base.html" %}

{% block title %}{% blocktrans with object.pk as build_id %}Delete build #{{ build_id }}{% endblocktrans %}{% endblock %}

{% block content %}
	<section>{% url "project" object.project.slug as project_url %}
		<h1>{% blocktrans with object.pk as build_id %}Delete build #{{ build_id }}?{% endblocktrans %}</h1>

		<p>{% blocktrans with build_id=object.pk project_name=object.project.name %}You are about to delete build #{{ build_id }} of <a href="{{ project_url }}">{{ project_name }}</a>.{% endblocktrans %}{% blocktrans count childs_count=object.builds.count %}{% plural %}This will delete the {{ childs_count }} elements of the build axes.{% endblocktrans %}</p>

		<form method="post" action="{% url "delete_build" object.project.slug object.pk %}">
			{% csrf_token %}
			<input type="submit" value="{% trans "Delete" %}">
			<a href="{% url "project" object.project.slug %}">{% trans "Cancel" %}</a>
		</form>
	</section>
{% endblock %}

ci/projects/templates/projects/build_detail.html
{% extends "base.html" %}
{% load truncate %}

{% block title %}{% blocktrans with object.pk as build_id %}Build #{{ build_id }} of {{ project }}{% endblocktrans %}{% endblock %}

{% block content %}
	<section class="build_summary">{% url "project" project.slug as project_url %}
		<h1>{% blocktrans with object.pk as build_id %}Build #{{ build_id }} of <a href="{{ project_url }}">{{ project }}</a>{% endblocktrans %}</h1>
		<p class="meta">{{ object.creation_date }} - <strong>{{ object.branch }}</strong>:{{ object.short_rev }}</p>
		<h6>{% trans "Build instructions" %}</h6>
		<pre>{{ object.build_instructions }}</pre>

		{% if object.matrix_data %}
			<h6>{% trans "Build axes" %}</h6>
			<ul>{% for key, values in object.matrix_data.items %}
					<li><strong>{{ key }}</strong>: {% for value in values %}{{ value }}{% if not forloop.last %}, {% endif %}{% endfor %}</li>
			{% endfor %}</ul>
		{% endif %}
	</section>

	<section class="build_status">
		<h2>
			<div class="title">{% trans "Build status:" %} {{ object.build_status }}</div>
			<div class="all"><a href="{% url "project_builds" project.slug %}">{% trans "all builds" %}</a></div>
		</h2>

		<ul>
			{% for job in object.jobs.all %}
				<li>
					<div class="name"><a href="{% url "project_job" project.slug object.pk job.pk %}">#{{ job.pk }}</a>
						<span>{% for key, val in job.values_data.items %}<strong>{{ key}}:</strong> {{ val }}{% if not forloop.last %}, {% endif %}{% endfor %}</span>
					</div>
					<div class="status {{ job.status }}"><span>{{ job.status }}</span></div>
				</li>
			{% endfor %}
		</ul>
		{% if object.build_status == "failed" or object.build_status = "success" %}
			<p class="delete"><a href="{% url "delete_build" object.project.slug object.pk %}">{% trans "Delete build" %}</a></p>
		{% endif %}

		<h2>{% trans "Changelog" %}</h2>
		<ul>
			{% for commit in object.history_data %}
				<li class="commit">
					<div class="rev">{{ commit.rev|truncatechars:"8" }} - {{ commit.author }}</div>
					<div class="message">{{ commit.message }}</div>
					<pre>{% for file in commit.files %}{{ file }}
{% endfor %}</pre>
				</li>
			{% endfor %}
		</ul>
	</section>
{% endblock %}

ci/projects/templates/projects/build_list.html
{% extends "base.html" %}

{% block title %}{% blocktrans %}Builds for {{ project }}{% endblocktrans %}{% endblock %}

{% block content %}
	<section class="build_status">{% url "project" project.slug as project_url %}
		<h1>{% blocktrans %}Builds for <a href="{{ project_url }}">{{ project }}</a>{% endblocktrans %}</h1>

		<ul>{% for build in object_list %}
				<li>
				<div class="name"><a href="{% url "project_build" project.slug build.pk %}">#{{ build.pk }}</a> <span class="date">{{ build.creation_date }}</span> <span class="revision"><strong>{{ build.branch }}</strong>:{{ build.short_rev }}</span></div>
					<div class="status {{ build.build_status }}"><span>{{ build.build_status }}</span></div>
				</li>
			{% empty %}
				<li>{% trans "This project hasn't been built yet." %}</li>
			{% endfor %}</ul>
	</section>
{% endblock %}

ci/projects/templates/projects/job_detail.html
{% extends "base.html" %}

{% block title %}{% blocktrans with object_pk=object.pk build_pk=object.build_id %}Job #{{ object_pk }} of build #{{ build_pk }}{% endblocktrans %}{% endblock %}

{% block content %}
	<section class="build">
		<h1>
			<div>{% blocktrans with object.pk as build_id %}Job #{{ build_id }}{% endblocktrans %}<span></div>
			<div class="status {{ object.status }}"><span>{{ object.status }}</span></div>
		</h1>
		<div class="meta">
			{% with object.build as build %}
				{% url "project" build.project.slug as project_url %}
				{% url "project_build" build.project.slug build.pk as build_url %}
				{% blocktrans with build.pk as build_id and build.project.name as name %}from build <a href="{{ build_url }}">#{{ build_id }}</a> of <a href="{{ project_url }}">{{ name }}</a>{% endblocktrans %}
			{% endwith %}
		</div>

		<div class="summary">
			{% if object.values_data %}
				<h6>{% trans "Configuration values" %}</h6>
				<ul>{% for key, value in object.values_data.items %}
						<li><strong>{{ key }}</strong>: {{ value }}</li>
				{% endfor %}</li>
			{% else %}
				&nbsp;
			{% endif %}
		</div>

		<div class="output">
			{% if object.xunit_xml_report %}
				<h6>{% trans "Test results" %}</h6>
				{% with object.xunit.summary as summary %}
					<p>Ran {{ summary.tests }} test{{ summary.tests|pluralize }}{% if summary.time %} in {{ summary.time }}s{% endif %}.</p>
					<p>{{ summary.failures }} failure{{ summary.failures|pluralize }},
					{{ summary.errors }} error{{ summary.errors|pluralize }}{% if summary.skip %}, 
					{{ summary.skip }} skipped{% endif %}.</p>
				{% endwith %}

				{% with object.xunit.testcases as testcases %}
					<ul class="test_results">
						<li>
							<div class="name"><strong>{% trans "Test name" %}</strong></div>
							<div class="status left"><strong>{% trans "Status" %}</strong></div>
							<div class="time"><strong>{% trans "Time" %}</strong></div>
						</li>
						{% for testcase in testcases %}
							<li>
								<div class="name" title="{{ testcase.desc }}">{{ testcase.classname }}.{{ testcase.name }}</div>
								<div class="status left {{ testcase.status }}"><span>{{ testcase.status }}</span></div>
								<div class="time">{{ testcase.time }}s</div>
								{% if testcase.text %}
									<div class="output">
										<pre>{{ testcase.text }}</pre>
									</div>
								{% endif %}
							</li>
						{% endfor %}
					</ul>
				{% endwith %}
			{% endif %}
			<h6>{% trans "Build output" %}</h6>
			<pre>{{ object.output }}</pre>
		</div>
	</section>
{% endblock %}

ci/projects/templates/projects/metabuild_confirm_delete.html
{% extends "base.html" %}

{% block title %}{% blocktrans with object.pk as build_id %}Delete build #{{ build_id }}{% endblocktrans %}{% endblock %}

{% block content %}
	<section>{% url "project" object.project.slug as project_url %}
		<h1>{% blocktrans with object.pk as build_id %}Delete build #{{ build_id }}?{% endblocktrans %}</h1>

		<p>{% blocktrans with build_id=object.pk project_name=object.project.name %}You are about to delete build #{{ build_id }} of <a href="{{ project_url }}">{{ project_name }}</a>.{% endblocktrans %}{% blocktrans count childs_count=object.builds.count %}{% plural %}This will delete the {{ childs_count }} elements of the build axes.{% endblocktrans %}</p>

		<form method="post" action="{% url "delete_build" object.project.slug object.pk %}">
			{% csrf_token %}
			<input type="submit" value="{% trans "Delete" %}">
			<a href="{% url "project" object.project.slug %}">{% trans "Cancel" %}</a>
		</form>
	</section>
{% endblock %}

ci/projects/templates/projects/metabuild_list.html
{% extends "base.html" %}

{% block title %}{% blocktrans %}Builds for {{ project }}{% endblocktrans %}{% endblock %}

{% block content %}
	<section class="build_status">{% url "project" project.slug as project_url %}
		<h1>{% blocktrans %}Builds for <a href="{{ project_url }}">{{ project }}</a>{% endblocktrans %}</h1>

		<ul>{% for build in object_list %}
				<li>
				<div class="name"><a href="{% url "project_build" project.slug build.pk %}">#{{ build.pk }}</a> <span class="date">{{ build.creation_date }}</span> <span class="revision">{{ build.short_rev }}</span></div>
					<div class="status {{ build.build_status }}"><span>{{ build.build_status }}</span></div>
				</li>
			{% empty %}
				<li>{% trans "This project hasn't been built yet." %}</li>
			{% endfor %}</ul>
	</section>
{% endblock %}

ci/projects/templates/projects/project_admin_form.html
{% extends "base.html" %}

{% block title %}{% blocktrans %}Build instructions for {{ object }}{% endblocktrans %}{% endblock %}

{% block content %}
	<section>
		<h1>{% blocktrans %}Build instructions for {{ object }}{% endblocktrans %}</h1>

		<form method="post" action="{% url "project_admin" object.slug %}">
			{% include "form.html" %}
			<p class="submit">
				<input type="submit" value="{% trans "Save" %}">
				<input type="submit" name="_continue" value="{% trans "Save and continue editing" %}">
				<a href="{% url "project" object.slug %}">{% trans "Cancel" %}</a>
			</p>
		</form>
	</section>

	<section class="axis">
		<h1>{% trans "Build axes" %}</h1>
		<form method="post" action="{% url "project_axis" object.slug %}">
			{{ formset.management_form }}
			{% for form in formset %}
				{% if forloop.last %}
					<h2>{% trans "Add a new build axis" %}</h2>
				{% else %}
					<h2>{% blocktrans with forloop.counter as ct %}Build axis #{{ ct}}{% endblocktrans %}</h2>
				{% endif %}
				{% include "form.html" %}
		{% endfor %}
			<p class="submit">
				<input type="submit" value="{% trans "Save" %}">
				<input type="submit" name="_addanother" value="{% trans "Save and add another axis" %}">
				<a href="{% url "project" object.slug %}">{% trans "Cancel" %}</a>
			</p>
		</form>
	</section>
{% endblock %}

ci/projects/templates/projects/project_detail.html
{% extends "base.html" %}

{% block title %}{{ object }}{% endblock %}

{% block content %}
	<section class="build_summary">
		<h1>{{ object }}{% if object.build_status != "running" %}
			<form method="post" action="{% url "project_trigger_build" object.slug %}">
				{% csrf_token %}
				<input type="submit" value="{% trans "Build now" %}">
			</form>
		{% endif %}</h1>

	<h6>{% blocktrans with object.get_repo_type_display as repo_type %}{{ repo_type }} repository{% endblocktrans %}</h6>
		<p>{{ object.repo|urlize }}</p>

		<h6>{% trans "Build instructions" %} (<a href="{% url "project_admin" object.slug %}">{% trans "Change" %}</a>)</h6>
		<pre>{{ object.build_instructions }}</pre>

		{% with object.configurations.all as axes %}
			{% if axes %}
				<h6>{% trans "Build axes" %}</h6>
				<ul>{% for config in axes %}
						<li><strong>{{ config }}</strong>: {% for val in config.values.all %}{{ val }}{% if not forloop.last %}, {% endif %}{% endfor %}</li>
				{% endfor %}</ul>
			{% endif %}
		{% endwith %}

		<h6>{% trans "Build URL" %}</h6>
		<p>{% trans "To build this project automatically on pushes, create a hook issuing a POST request to this URL:" %} <pre>http://{{ site.domain }}{% url "project_trigger_build" object.slug %}</pre>

		<h6>{% trans "Branches to build" %}</h6>
		<p>{{ object.get_build_branches_display }} ({% if object.build_branches == object.ALL_BRANCHES %}{% for branch in object.vcs.branches %}{{ branch }}{% if not forloop.last %}, {% endif %}{% endfor %}{% else %}{{ object.vcs.default_branch }}{% endif %})</p>
	</section>

	<section class="build_status">
		<h2>
			<div class="title">{% trans "Build status:" %} {{ object.build_status }}</div>
			<div class="all"><a href="{% url "project_builds" object.slug %}">{% trans "all builds" %}</a></div>
		</h2>

		<ul>
			{% for build in last_build.jobs.all %}
				<li>
					<div class="name"><a href="{% url "project_job" object.slug last_build.pk build.pk %}">#{{ build.pk }}</a>
						<span><strong>{{ last_build.branch}}</strong>:{{ last_build.short_rev }}</span>
						<span>{% for key, val in build.values_data.items %}<strong>{{ key}}:</strong> {{ val }}{% if not forloop.last %}, {% endif %}{% endfor %}</span>
					</div>
					<div class="status {{ build.status }}"><span>{{ build.status }}</span></div>
				</li>
			{% endfor %}
		</ul>

		{% if last_build %}
			{% if object.build_status == "failed" or object.build_status = "success" %}
				<p class="delete"><a href="{% url "delete_build" object.slug last_build.pk %}">{% trans "Delete build" %}</a></p>
			{% endif %}
		{% endif %}
	</section>
{% endblock %}

ci/projects/templates/projects/project_form.html
{% extends "base.html" %}

{% block title %}{% trans "Add a new project" %}{% endblock %}

{% block content %}
	<section>
		<h1>{% trans "Add a new project" %}</h1>

		<form method="post" action="{% url "add_project" %}">
			{% include "form.html" %}
			<p class="submit">
				<input type="submit" value="{% trans "Add" %}">
				<a href="{% url "projects" %}">{% trans "Cancel" %}</a>
			</p>
		</form>
	</section>
{% endblock %}

ci/projects/templates/projects/project_list.html
{% extends "base.html" %}

{% block content %}
	<section class="builds">
		<h1>
			<div class="name"><span>{% trans "Project" %}</span></div>
			<div class="lastbuild"><span>{% trans "Last build" %}</span></div>
			<div class="status"><span>{% trans "Build status" %}</span></div>
		</h1>
		<ul>
			{% for project in object_list %}
				<li>
					<div class="name"><span><a href="{% url "project" project.slug %}">{{ project }}</a></span></div>
					<div class="lastbuild">
						{% with project.builds.all.0.creation_date as build_date %}
							{% if build_date %}
								{% with build_date|timesince as time_since %}
									<span title="{{ build_date }}"><a href="{% url "project" project.slug %}">{% blocktrans %}{{ time_since }} ago{% endblocktrans %}</a></span>
								{% endwith %}
							{% else %}
								<span>{% trans "None" %}</span>
							{% endif %}
						{% endwith %}
					</div>
					<div class="status {{ project.build_status}}"><span>{{ project.build_status }}</span>{% if project.build_status == "running" %} {{ project.build_progress }}{% endif %}</div>
				</li>
			{% empty %}
				<li class="empty">{% trans "You don't have any project yet." %}</li>
			{% endfor %}
		</ul>
		<div class="actions">
			<span><a href="{% url "add_project" %}">{% trans "Add a new project" %}</a></span>
		</div>
	</section>
{% endblock %}